packages:
  - example/*
  - packages/*
  - sites/*

allowBuilds:
  '@prisma/engines': true
  '@swc/core': true
  better-sqlite3@12.11.1: true
  better-sqlite3@13.0.3: false
  esbuild: true
  msgpackr-extract: true
  prisma: true
  sharp: true
  unrs-resolver: true
  workerd: true

catalog:
  react: 19.3.0
  react-dom: 19.3.0
  '@types/react': 19.3.0
  '@types/react-dom': 19.3.0
  vite: npm:@voidzero-dev/vite-plus-core@1.0.0
  vite-plus: 1.0.0
  vitest: 5.0.2
  '@vitest/coverage-v8': 5.0.2

onlyBuiltDependencies:
  - '@prisma/client'
  - '@prisma/engines'
  - '@swc/core'
  - '@tailwindcss/oxide'
  - better-sqlite3
  - esbuild
  - msgpackr-extract
  - prisma
  - sharp
  - unrs-resolver
  - workerd

overrides:
  '@cloudflare/workers-types': 5.20260904.1
  better-auth: 1.7.2
  drizzle-orm: 0.45.3
  kysely: 0.28.17
  pg: 8.23.0
  vite@*: 'catalog:'
  vitest@*: 'catalog:'

peerDependencyRules:
  allowAny:
    - vite
    - vitest
  allowedVersions:
    vite: '*'
    vitest: '*'

minimumReleaseAgeExclude:
  - '@nkzw/*'
  - '@void/*'
  - 'void'
  - '@voidzero-dev/vite-plus-core@0.3.3'
  - '@voidzero-dev/vite-plus-darwin-arm64@0.3.3'
  - '@voidzero-dev/vite-plus-darwin-x64@0.3.3'
  - '@voidzero-dev/vite-plus-linux-arm64-gnu@0.3.3'
  - '@voidzero-dev/vite-plus-linux-arm64-musl@0.3.3'
  - '@voidzero-dev/vite-plus-linux-x64-gnu@0.3.3'
  - '@voidzero-dev/vite-plus-linux-x64-musl@0.3.3'
  - '@voidzero-dev/vite-plus-win32-arm64-msvc@0.3.3'
  - '@voidzero-dev/vite-plus-win32-x64-msvc@0.3.3'
  - vite-plus@0.3.3
  - '@cloudflare/codemods@0.2.1'
  - cf@1.0.0-beta.5
  - preact-suspense@0.3.2
