/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck
/*
 * This file exports all enum related types from the schema.
 *
 * 🟢 You can import this file directly.
 */

export const RSVPStatus = {
  INVITED: 'INVITED',
  GOING: 'GOING',
  INTERESTED: 'INTERESTED',
  DECLINED: 'DECLINED',
} as const;

export type RSVPStatus = (typeof RSVPStatus)[keyof typeof RSVPStatus];

export const EventType = {
  WORKSHOP: 'WORKSHOP',
  MEETUP: 'MEETUP',
  AMA: 'AMA',
  LAUNCH: 'LAUNCH',
  COMMUNITY_CALL: 'COMMUNITY_CALL',
} as const;

export type EventType = (typeof EventType)[keyof typeof EventType];
