packages:
  - client
  - server

allowBuilds:
  '@prisma/engines': true
  '@swc/core': true
  better-sqlite3: true
  esbuild: true
  prisma: true
  sharp: true
  workerd: true

catalog:
  vite: npm:@voidzero-dev/vite-plus-core@^0.1.23
  vite-plus: ^0.1.23
  vitest: npm:@voidzero-dev/vite-plus-test@^0.1.23

minimumReleaseAgeExclude:
  - '@voidzero-dev/vite-plus-core'
  - '@voidzero-dev/vite-plus-test'
  - vite-plus

onlyBuiltDependencies:
  - '@prisma/client'
  - '@prisma/engines'
  - '@swc/core'
  - '@tailwindcss/oxide'
  - esbuild
  - msgpackr-extract
  - prisma
  - unrs-resolver

overrides:
  vite: 'catalog:'
  vitest: 'catalog:'

peerDependencyRules:
  allowAny:
    - vite
    - vitest
  allowedVersions:
    vite: '*'
    vitest: '*'
