export function createFateClient(...args: Array<never>): never {
  throw new Error(
    `@nkzw/fate/client is generated by the fate Vite plugin. Add fate({ module: '...' }) to your Vite config.`,
  );
}
